from __future__ import annotations

from pathlib import Path
from shutil import copyfile

from ase import Atoms


TEMPLATE_NAMES = ("INCAR", "KPOINTS", "sub")


def write_job_folder(
    output_dir: str | Path,
    atoms: Atoms,
    flags: list[tuple[bool, bool, bool]],
    element_order: list[str],
    template_dir: str | Path,
    potcar_command_template: str,
    overwrite: bool = False,
    coordinate_mode: str = "Direct",
) -> None:
    destination = Path(output_dir)
    if destination.exists() and any(destination.iterdir()) and not overwrite:
        raise FileExistsError(f"Output folder already exists and is not empty: {destination}")
    destination.mkdir(parents=True, exist_ok=True)

    write_poscar(destination / "POSCAR", atoms, flags, element_order, coordinate_mode)
    copy_templates(template_dir, destination)
    write_potcar_instruction(destination / "POTCAR_COMMAND.txt", element_order, potcar_command_template)


def copy_templates(template_dir: str | Path, destination: Path) -> None:
    template_path = Path(template_dir)
    for name in TEMPLATE_NAMES:
        source = template_path / name
        if not source.exists():
            raise FileNotFoundError(f"Missing template: {source}")
        copyfile(source, destination / name)


def write_potcar_instruction(path: Path, element_order: list[str], command_template: str) -> None:
    elements = " ".join(element_order)
    command = command_template.format(elements=elements)
    path.write_text(
        "Run this on Raven after copying the job folder.\n"
        f"Element order: {elements}\n"
        f"Command: {command}\n",
        encoding="utf-8",
    )


def write_poscar(
    path: str | Path,
    atoms: Atoms,
    flags: list[tuple[bool, bool, bool]],
    element_order: list[str],
    coordinate_mode: str = "Direct",
) -> None:
    if len(atoms) != len(flags):
        raise ValueError("Number of selective dynamics flags must match atom count")
    if coordinate_mode not in {"Direct", "Cartesian"}:
        raise ValueError("coordinate_mode must be 'Direct' or 'Cartesian'")

    symbols = atoms.get_chemical_symbols()
    counts = [symbols.count(symbol) for symbol in element_order]
    positions = atoms.get_scaled_positions(wrap=False) if coordinate_mode == "Direct" else atoms.get_positions()

    lines = [
        "Generated by DFT job submission workflow",
        "1.00000000000000",
    ]
    for vector in atoms.cell.array:
        lines.append(_format_vector(vector))
    lines.append("  " + "  ".join(element_order))
    lines.append("  " + "  ".join(str(count) for count in counts))
    lines.append("Selective dynamics")
    lines.append(coordinate_mode)

    for position, flag in zip(positions, flags):
        flag_text = "   ".join("T" if value else "F" for value in flag)
        lines.append(
            f"  {position[0]: .16f}  {position[1]: .16f}  {position[2]: .16f}   {flag_text}"
        )

    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _format_vector(vector) -> str:
    return f"  {vector[0]: .16f}  {vector[1]: .16f}  {vector[2]: .16f}"
